import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface StudentRow {
  full_name: string;
  email: string;
  phone_whatsapp: string;
  course_applying_for: string;
  status: string;
  country: string;
  created_at: string;
}

const C = {
  primary: [29, 29, 31] as [number, number, number],
  accent: [137, 64, 250] as [number, number, number],
  muted: [142, 142, 147] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

export function generateStudentReportPDF(
  students: StudentRow[],
  exportedBy: string = "Admin",
): jsPDF {
  const doc = new jsPDF("landscape", "mm", "a4");
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  // ── Cover Page ──
  doc.setFillColor(137, 64, 250);
  doc.rect(0, 0, W, 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(29, 29, 31);
  doc.text("Beyund Labs Academy", W / 2, 50, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.setTextColor(142, 142, 147);
  doc.text("Student Report", W / 2, 62, { align: "center" });

  doc.setDrawColor(137, 64, 250);
  doc.setLineWidth(0.8);
  doc.line(W / 2 - 30, 70, W / 2 + 30, 70);

  doc.setFontSize(11);
  doc.setTextColor(29, 29, 31);
  const metaY = 85;

  doc.setFont("helvetica", "bold");
  doc.text("Export Date:", 60, metaY);
  doc.setFont("helvetica", "normal");
  doc.text(`${dateStr} at ${timeStr}`, 95, metaY);

  doc.setFont("helvetica", "bold");
  doc.text("Exported By:", 60, metaY + 8);
  doc.setFont("helvetica", "normal");
  doc.text(exportedBy, 95, metaY + 8);

  doc.setFont("helvetica", "bold");
  doc.text("Total Students:", 60, metaY + 16);
  doc.setFont("helvetica", "normal");
  doc.text(`${students.length}`, 95, metaY + 16);

  // Status breakdown
  const statusCounts: Record<string, number> = {};
  students.forEach((s) => { statusCounts[s.status] = (statusCounts[s.status] || 0) + 1; });

  const statusKeys = ["enrolled", "pending", "contacted", "rejected"];
  const statusLabels = ["Enrolled", "Pending", "Contacted", "Rejected"];
  const statusRGB: Record<string, [number, number, number]> = {
    enrolled: [48, 185, 78], pending: [255, 159, 10],
    contacted: [0, 122, 255], rejected: [255, 69, 58],
  };

  doc.setFontSize(10);
  let sy = metaY + 30;
  doc.setFont("helvetica", "bold");
  doc.text("Status Breakdown:", 60, sy);
  doc.setFont("helvetica", "normal");
  sy += 7;
  statusKeys.forEach((key, i) => {
    const c = statusRGB[key];
    doc.setFillColor(c[0], c[1], c[2]);
    doc.roundedRect(60, sy - 4, 3, 3, 0.5, 0.5, "F");
    doc.setTextColor(29, 29, 31);
    doc.text(`${statusLabels[i]}: ${statusCounts[key] || 0}`, 67, sy);
    sy += 6;
  });

  // Cover footer
  doc.setFontSize(8);
  doc.setTextColor(142, 142, 147);
  doc.text("Confidential — For internal use only", W / 2, H - 15, { align: "center" });
  doc.text("Generated by Beyund Labs Academy LMS", W / 2, H - 10, { align: "center" });

  // ── Data Pages ──
  doc.addPage();
  drawDataHeader(doc, W, dateStr);

  const tableData = students.map((s, i) => [
    `${i + 1}`,
    s.full_name || "-",
    s.email || "-",
    s.phone_whatsapp || "-",
    s.course_applying_for || "-",
    s.status.charAt(0).toUpperCase() + s.status.slice(1),
    s.country || "-",
    new Date(s.created_at).toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" }),
  ]);

  autoTable(doc, {
    startY: 18,
    margin: { left: 10, right: 10 },
    head: [["#", "Full Name", "Email", "WhatsApp", "Course", "Status", "Country", "Date"]],
    body: tableData,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 3, textColor: [29, 29, 31], lineColor: [204, 204, 209], lineWidth: 0.3 },
    headStyles: { fillColor: [242, 242, 247], textColor: [29, 29, 31], fontStyle: "bold", fontSize: 8, cellPadding: 4 },
    alternateRowStyles: { fillColor: [249, 249, 251] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 45 }, 2: { cellWidth: 55 }, 3: { cellWidth: 35 },
      4: { cellWidth: 40 }, 5: { cellWidth: 25, halign: "center" },
      6: { cellWidth: 30 }, 7: { cellWidth: 25 },
    },
    didDrawPage: (data) => {
      drawDataHeader(doc, W, dateStr);
      doc.setFontSize(7);
      doc.setTextColor(142, 142, 147);
      doc.text(`Page ${getNumPages(doc)}`, W / 2, H - 5, { align: "center" });
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const val = (data.cell.raw as string).toLowerCase();
        const colorMap: Record<string, [number, number, number]> = {
          enrolled: [48, 185, 78], pending: [255, 159, 10],
          contacted: [0, 122, 255], rejected: [255, 69, 58],
        };
        if (colorMap[val]) {
          data.cell.styles.textColor = colorMap[val];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  // Page numbers
  const totalPages = getNumPages(doc);
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(142, 142, 147);
    doc.text(`Page ${i} of ${totalPages} — Beyund Labs Academy LMS`, W / 2, H - 5, { align: "center" });
  }

  return doc;
}

function drawDataHeader(doc: jsPDF, W: number, dateStr: string) {
  doc.setFillColor(29, 29, 31);
  doc.rect(0, 0, W, 12, "F");
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Beyund Labs Academy — Student Report", 10, 8);
  doc.setFont("helvetica", "normal");
  doc.text(dateStr, W - 10, 8, { align: "right" });
}

// jsPDF getNumberOfPages exists at runtime but may not be in types
function getNumPages(doc: jsPDF): number {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (doc as any).getNumberOfPages();
}

export function downloadPDF(
  students: StudentRow[],
  exportedBy: string = "Admin"
): { blob: Blob; fileName: string; dateStr: string } {
  const doc = generateStudentReportPDF(students, exportedBy);
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];
  const fileName = `Student_Report_${dateStr}_${now.getTime()}.pdf`;
  const blob = doc.output("blob");
  return { blob, fileName, dateStr: `${dateStr} ${now.toLocaleTimeString()}` };
}